# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-30 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='total_fedeed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisation',
            name='total_times_donated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
