# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-29 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('district', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('organisations', models.CharField(choices=[('D', 'Donor'), ('F', 'Feeder')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('0', 'RAW'), ('1', 'FRESH'), ('2', 'OLD')], max_length=1)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('itime', models.DateTimeField(auto_now_add=True)),
                ('finaltime', models.DateTimeField(blank=True)),
                ('landmark', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('dist', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin', models.PositiveIntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
