# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20200130_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisations',
            field=models.CharField(choices=[('D', 'Donor'), ('F', 'Feeder'), ('F', 'Farmer'), ('LP', 'Logestic Provider')], max_length=1),
        ),
    ]
