# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('crop_name', models.CharField(max_length=120)),
                ('time_type', models.CharField(choices=[('m_1', '1 Month'), ('m_3', '3 Months'), ('m_6', '6 Month'), ('m_12', '12 Month')], max_length=1)),
            ],
        ),
    ]
